# No need to explicitly write this on your .gitlab-ci.yml file.
# Add and edit if you want different stage configurations.
stages:
  - build
  - test
  - deploy

image: lorisleiva/laravel-docker:latest

# The job's name.
composer:

  # The job's stage (build, test or deploy).
  stage: build

  # What to run on the job.
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
    # ...
  artifacts:

      # (Optional) Give it an expiration date,
      # after that period you won't be able to
      # download them via the UI anymore.
    expire_in: 1 month

        # Define what to output from the job.
    paths:
      - vendor/
      - .env
phpunit:
  stage: test
  # List of jobs from which it will download the artifacts.
  dependencies:
    - composer
  script:
    - phpunit --coverage-text --colors=never
    - php artisan test
